### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by minikin** [DavidLGoldberg/qolor#24]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [qolor](https://github.com/davidlgoldberg/qolor) package, v0.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'includes' of undefined

```
At /Users/Minikin/.atom/packages/qolor/lib/qolor-view.coffee:20

TypeError: Cannot read property 'includes' of undefined
  at /Users/Minikin/.atom/packages/qolor/lib/qolor-view.coffee:20:33
  at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1427:25

```
### Commands

```
     -9:57.4.0 core:copy (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
     -8:05.4.0 nuclide-remote-projects:connect (span.)
     -7:40.9.0 core:paste (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
  2x -7:39.1.0 core:backspace (atom-text-editor.atom-text-editor-unstyled.mini.is-focused)
     -7:06.5.0 nuclide-remote-projects:connect (span.)
     -5:33.7.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
     -1:04.5.0 nuclide-remote-projects:connect (div.nuclide-file-tree.focusable-panel.tree-view)
     -0:36 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -0:35 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "telemetryConsent": "no"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (active)
dash, v1.7.0 (inactive)
file-icons, v1.7.22 (active)
fonts, v1.6.0 (active)
linter, v1.11.18 (active)
nuclide, v0.176.0 (active)
nuclide-remote-projects, v0.0.0 (active)
nuclide-type-hint, v0.0.0 (active)
oceanic-next, v0.4.0 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.37.0 (active)
pretty-json, v1.6.1 (active)
qolor, v0.4.0 (active)
react-snippets, v0.5.0 (active)
redux-snippets, v0.2.2 (active)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by DavidLGoldberg** [comment]
I haven't heard much activity about this one, haven't gotten a chance to look, did the problem go away?

I was toying with the idea of trying all of those packages, haven't gotten around to it.

**Comment by DavidLGoldberg** [comment]
Maybe it's the nuclide, and perhaps in conjunction with that toggle comments or something.  I'll leave it on here, if I get a chance.

**Comment by formatme** [comment]
also got this

C:\Users\formatme\.atom\packages\qolor\lib\qolor-view.coffee:20
Hide Stack Trace
TypeError: Cannot read property 'includes' of undefined
    at file:///C:/Users/formatme/.atom/packages/qolor/lib/qolor-view.coffee:20:33
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\formatme\AppData\Local\atom\app-1.19.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\formatme\AppData\Local\atom\app-1.19.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidStopChangingEvent (C:\Users\formatme\AppData\Local\atom\app-1.19.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1571:26)
    at later (C:\Users\formatme\AppData\Local\atom\app-1.19.1\resources\app\node_modules\text-buffer\lib\helpers.js:21:13)

**Comment by DavidLGoldberg** [comment]
Interesting.  Could either of you give me any more information by any chance?

@formatme Have you ever had Qolor working?  What OS + Atom version?  Do you get a message about incompatible packages (this has been a thing for a few packages for me recently) cmd+shift+p -> incompatible packages should bring you to a dialog to rebuild any old builds.  (Strange I know!)

Thanks for reporting appreciate it!

**Comment by minikin** [comment]
@DavidLGoldberg  I'll try to help you over the weekend.

**Comment by DavidLGoldberg** [comment]
That would be amazing thanks!

**Comment by Exelord** [comment]
Petty annoying issue also using teletype :/

**Comment by DavidLGoldberg** [comment]
@Exelord , sorry just seeing this now some how.... Hmm..... I've used teletype only once so haven't tried it with qolor, thanks for the heads up.  I'll take a look.  This is on my radar now.

**Comment by DavidLGoldberg** [comment]
@Exelord I took a look at this...wasn't able to reproduce (although didn't have a buddy to teletype with..) I'll get that going this week, assuming it will jump out?

Or are there specific steps?
